//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientesEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ADDRESS> ADDRESSes { get; set; }
        public DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public DbSet<ITEM> ITEMS { get; set; }
        public DbSet<ORDER> ORDERS { get; set; }
        public DbSet<PASSWD_CHANGE_REQUEST> PASSWD_CHANGE_REQUEST { get; set; }
    }
}
