//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientesEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public int ITEMID { get; set; }
        public decimal PRODID { get; set; }
        public string PRODUCTNAME { get; set; }
        public string PARTNUM { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<int> QUANTITY { get; set; }
        public int ORDID { get; set; }
    
        public virtual ORDER ORDER { get; set; }
    }
}
