//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientesEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public ORDER()
        {
            this.ITEMS = new HashSet<ITEM>();
        }
    
        public string CUSTID { get; set; }
        public int ORDID { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public string STATUS { get; set; }
        public string COMMENTS { get; set; }
        public string CARRIER { get; set; }
        public Nullable<System.DateTime> LASTTRACKINGDATE { get; set; }
        public string VENDOR { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual ICollection<ITEM> ITEMS { get; set; }
    }
}
