//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientesEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PASSWD_CHANGE_REQUEST
    {
        public int ID { get; set; }
        public string CUSTID { get; set; }
        public string EMAIL { get; set; }
        public string TOKEN { get; set; }
        public System.DateTime REQUEST_DATE { get; set; }
        public string PROCESSED { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
