version: '3'
services:
  product_service:
    build: "ProductService/."
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "7076:8080"
    networks:
      - "service-compose-net"
networks:
  service-compose-net:
    driver: bridge