//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdenesBC.ValidateCreditCardSVC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://card.com.co/", ConfigurationName="ValidateCreditCardSVC.ValidateCreditCard")]
    public interface ValidateCreditCard {
        
        // CODEGEN: Generating message contract since the operation VerifyCC is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="error", Namespace="http://card.com.co/CreditCardValidation")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        OrdenesBC.ValidateCreditCardSVC.VerifyCCResponse VerifyCC(OrdenesBC.ValidateCreditCardSVC.CreditCardInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<OrdenesBC.ValidateCreditCardSVC.VerifyCCResponse> VerifyCCAsync(OrdenesBC.ValidateCreditCardSVC.CreditCardInfo request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2116.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://card.com.co/CreditCardValidation")]
    public partial class CreditCard : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ccTypeField;
        
        private string ccNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string ccType {
            get {
                return this.ccTypeField;
            }
            set {
                this.ccTypeField = value;
                this.RaisePropertyChanged("ccType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ccNum {
            get {
                return this.ccNumField;
            }
            set {
                this.ccNumField = value;
                this.RaisePropertyChanged("ccNum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreditCardInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://card.com.co/CreditCardValidation", Order=0)]
        public OrdenesBC.ValidateCreditCardSVC.CreditCard CreditCard;
        
        public CreditCardInfo() {
        }
        
        public CreditCardInfo(OrdenesBC.ValidateCreditCardSVC.CreditCard CreditCard) {
            this.CreditCard = CreditCard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyCCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://card.com.co/CreditCardValidation", Order=0)]
        public bool valid;
        
        public VerifyCCResponse() {
        }
        
        public VerifyCCResponse(bool valid) {
            this.valid = valid;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidateCreditCardChannel : OrdenesBC.ValidateCreditCardSVC.ValidateCreditCard, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidateCreditCardClient : System.ServiceModel.ClientBase<OrdenesBC.ValidateCreditCardSVC.ValidateCreditCard>, OrdenesBC.ValidateCreditCardSVC.ValidateCreditCard {
        
        public ValidateCreditCardClient() {
        }
        
        public ValidateCreditCardClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidateCreditCardClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateCreditCardClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidateCreditCardClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrdenesBC.ValidateCreditCardSVC.VerifyCCResponse OrdenesBC.ValidateCreditCardSVC.ValidateCreditCard.VerifyCC(OrdenesBC.ValidateCreditCardSVC.CreditCardInfo request) {
            return base.Channel.VerifyCC(request);
        }
        
        public bool VerifyCC(OrdenesBC.ValidateCreditCardSVC.CreditCard CreditCard) {
            OrdenesBC.ValidateCreditCardSVC.CreditCardInfo inValue = new OrdenesBC.ValidateCreditCardSVC.CreditCardInfo();
            inValue.CreditCard = CreditCard;
            OrdenesBC.ValidateCreditCardSVC.VerifyCCResponse retVal = ((OrdenesBC.ValidateCreditCardSVC.ValidateCreditCard)(this)).VerifyCC(inValue);
            return retVal.valid;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrdenesBC.ValidateCreditCardSVC.VerifyCCResponse> OrdenesBC.ValidateCreditCardSVC.ValidateCreditCard.VerifyCCAsync(OrdenesBC.ValidateCreditCardSVC.CreditCardInfo request) {
            return base.Channel.VerifyCCAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrdenesBC.ValidateCreditCardSVC.VerifyCCResponse> VerifyCCAsync(OrdenesBC.ValidateCreditCardSVC.CreditCard CreditCard) {
            OrdenesBC.ValidateCreditCardSVC.CreditCardInfo inValue = new OrdenesBC.ValidateCreditCardSVC.CreditCardInfo();
            inValue.CreditCard = CreditCard;
            return ((OrdenesBC.ValidateCreditCardSVC.ValidateCreditCard)(this)).VerifyCCAsync(inValue);
        }
    }
}
