package co.com.pica.kallsonys;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630262
 * 2017-09-20T18:47:59.023-05:00
 * Generated source version: 3.1.5.redhat-630262
 * 
 */
@WebServiceClient(name = "OrdenEndpointService", 
                  wsdlLocation = "file:/C:/Users/DELL/Documents/PROYECTOS%20FUSE/tallerSOA/serviceOrders/src/main/resources/envioOrden.wsdl",
                  targetNamespace = "http://kallSonys.pica.com.co") 
public class OrdenEndpointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://kallSonys.pica.com.co", "OrdenEndpointService");
    public final static QName OrdenBinding = new QName("http://kallSonys.pica.com.co", "OrdenBinding");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/DELL/Documents/PROYECTOS%20FUSE/tallerSOA/serviceOrders/src/main/resources/envioOrden.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrdenEndpointService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/DELL/Documents/PROYECTOS%20FUSE/tallerSOA/serviceOrders/src/main/resources/envioOrden.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrdenEndpointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrdenEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrdenEndpointService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public OrdenEndpointService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public OrdenEndpointService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public OrdenEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns OrderEndpoint
     */
    @WebEndpoint(name = "OrdenBinding")
    public OrderEndpoint getOrdenBinding() {
        return super.getPort(OrdenBinding, OrderEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderEndpoint
     */
    @WebEndpoint(name = "OrdenBinding")
    public OrderEndpoint getOrdenBinding(WebServiceFeature... features) {
        return super.getPort(OrdenBinding, OrderEndpoint.class, features);
    }

}
