package co.com.pica.kallsonys;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.5.redhat-630262
 * 2017-09-20T18:47:58.973-05:00
 * Generated source version: 3.1.5.redhat-630262
 * 
 */
@WebService(targetNamespace = "http://kallSonys.pica.com.co", name = "OrderEndpoint")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OrderEndpoint {

    @WebMethod
    @WebResult(name = "mensajeSalida", targetNamespace = "http://kallSonys.pica.com.co", partName = "out")
    public MensajeSalida enviarOrden(
        @WebParam(partName = "in", name = "mensajeEntrada", targetNamespace = "http://kallSonys.pica.com.co")
        MEntrada in
    );
}
