server:
    port: 7076
spring:
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:sqlserver://LAPTOP-MICHAEL\SQLSERVER2008R2;database=product-service
        username: michael
        password: michael
        hikari:
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.SQLServer2012Dialect
        database: SQL_SERVER
        show-sql: false
        properties:
            hibernate.id.new_generator_mappings: true
#            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
#            hibernate.hbm2ddl.auto: create
#            hibernate.cache.region.factory_class: net.sf.ehcache.hibernate.EhCacheRegionFactory
#            hibernate.cache.region.factory_class: io.github.jhipster.config.jcache.NoDefaultJCacheRegionFactory
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

jhipster:
    cache: # Cache configuration
        ehcache: # Ehcache configuration
            time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
            max-entries: 1000 # Number of objects in each cache entry