version: '3'
services:
  product_service:
    image: mfrondon/asperisk-product:0.0.2
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 300M
#      restart_policy:
#        condition: on-failure
    ports:
      - "7076:7076"
    networks:
      - webnet2
networks:
  webnet2: