version: '3'
services:
  product_service:
#    build: "ProductService/."
    image: mfrondon/asperisk-product:0.0.1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "7076:8080"
    networks:
      - "asperisk-overlay-compose-webnet"
networks:
  asperisk-overlay-compose-webnet:
#    driver: overlay